### ISSUE TITLE
Seg Fault

### ISSUE THREAD

**Issue by joaojoyce** [seemk/TileLite#1]
Hi! Thank you for this project. This looks like a great idea.

I'm getting a "Segmentation fault (core dumped)" when running, any idea what might be happening? 
Have you run into this issue?

**Comment by seemk** [comment]
Hi, are you running on Linux or OSX? Also are you compiling with Mapnik or without (-DWITH_MAPNIK=OFF)?

**Comment by naoliv** [comment]
I can see one segfault when simply running it with the default config `./tilesweep -c conf.ini`, accessing the control panel http://localhost:8080/ and clicking at `Start`

gdb's `thread apply all bt full` [can be seen here](https://github.com/seemk/TileSweep/files/2367707/gdb.txt)

**Comment by seemk** [comment]
Thanks for the gdb output. The issue should be fixed in 5c4f94c. Now when rendering is enabled and Mapnik's initialization fails, TileSweep exits.
