### ISSUE TITLE
Some issues found by cppcheck

### ISSUE THREAD

**Issue by naoliv** [seemk/TileLite#2]
I am unsure if they are all valid issues, but it's worth to verify:

    [tilesweep/src/poly_fill.c:70]: (error) Overflow in pointer arithmetic, NULL pointer is subtracted.
    [tilesweep/src/poly_fill.c:111]: (error) Invalid calloc() argument nr 1. The value is 0 but the valid values are '1:'.
    [tilesweep/src/tilesweep.c:687]: (error) Memory leak: startup_tasks
    [tilesweep/src/tilesweep.c:687]: (error) Memory leak: rc_args
    [tilesweep/src/tilesweep.c:710]: (error) Memory leak: startup_tasks
    [tilesweep/src/tilesweep.c:710]: (error) Memory leak: rc_args

**Comment by seemk** [comment]
Thanks for the analysis! The first two should only happen when there is no memory left, however both code paths use sb_push, which causes a segfault if memory can't be allocated (see https://github.com/seemk/TileSweep/blob/master/tilesweep/src/stretchy_buffer.h#L213). However, I am not sure if it's worth checking the out of memory conditions there, as the default logic would be to exit anyway.

As for the error's in tilesweep.c, they happen inside main, so the memory is reclaimed by OS when the program exits early. This should not be a problem.
